# Generated by Django 4.0.1 on 2022-01-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailable',
            name='fromTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='doctoravailable',
            name='toTime',
            field=models.DateTimeField(),
        ),
    ]
