# Generated by Django 4.0.1 on 2022-01-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_doctoravailable_fromtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailable',
            name='fromTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctoravailable',
            name='toTime',
            field=models.TimeField(),
        ),
    ]
